stages:
  - terraform
  - build
  - deploy

variables:
  PROJECT_ID: "ton-project-gcp"
  REGION: "us-central1"
  SERVICE_NAME: "fastapi-cloudrun"
  IMAGE_NAME: "gcr.io/$PROJECT_ID/$SERVICE_NAME"
  TF_WORKING_DIR: "terraform"   # dossier où se trouve ta conf terraform

before_script:
  # Installer Google Cloud SDK
  - echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > gcloud-key.json
  - curl -sSL https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud auth activate-service-account --key-file=gcloud-key.json
  - gcloud config set project $PROJECT_ID
  - gcloud auth configure-docker

terraform:
  stage: terraform
  image: hashicorp/terraform:light
  script:
    - cd $TF_WORKING_DIR
    - terraform init
    - terraform validate
    - terraform apply -auto-approve
  only:
    - main

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - main

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - gcloud run deploy $SERVICE_NAME --image $IMAGE_NAME --region $REGION --platform managed --allow-unauthenticated
  only:
    - main
