
name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker image
      run: |
        docker build -t fastapi ./app
        docker tag fastapi:latest ${{ steps.login-ecr.outputs.registry }}/fastapi:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/fastapi:latest

    - name: Terraform Init & Apply
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve
