stages:
  - build
  - deploy

variables:
  AWS_REGION: "us-east-1"
  IMAGE_NAME: "fastapi"
  ECR_REGISTRY: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
  TF_DIR: "infra"

before_script:
  - apk add --no-cache python3 py3-pip docker curl bash
  - pip3 install awscli
  - aws --version
  - aws sts get-caller-identity

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - $(aws ecr get-login --no-include-email --region $AWS_REGION)
    - docker build -t $IMAGE_NAME ./app
    - docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
    - docker push $ECR_REGISTRY/$IMAGE_NAME:latest

deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: [""]
  script:
    - cd $TF_DIR
    - terraform init
    - terraform apply -auto-approve
